name: ripple_viewer_env
channels:
  - conda-forge
dependencies:
  - av
  - blosc
  - cython
  - daal4py
  - decorator==5.1.1
  - dill
  - fastcore
  - hdbscan
  - icc_rt
  - imageio
  - ipykernel
  - jinja2
  - joblib
  - line_profiler
  - lmfit
  - loky
  - matplotlib
  - mkl
  - mkl_fft
  - msgpack-python
  - numba
  - numpy==1.22
  - openpyxl
  - pandas
  - psutil
  - pyaudio
  - PyDrive2
  - pyopencl
  - pyopengl>=3.1.6
  - pyqt>=5.12
  - pyserial
  - python-neo>=0.9
  - python==3.8.5
  - pyyaml
  - pyzmq
  - scikit-learn
  - scipy
  - seaborn
  - toml
  - tqdm
  - vispy>=0.9
  - websockets
  - yappi
  - pip:
    - PyOpenGL-accelerate==3.1.6
    - PySide6==6.3.1
    - git+https://www.github.com/rdarie/pyqtgraph.git#egg=pyqtgraph
    - git+https://www.github.com/rdarie/ephyviewer.git@rippleViewerV2#egg=ephyviewer
    - git+https://www.github.com/rdarie/pyacq.git#egg=pyacq
    - git+https://www.github.com/rdarie/rippleViewer.git#egg=pyRippleViewer
    - external_wheels\windows\xipppy-0.16.19-cp38-cp38-win_amd64.whl