FROM continuumio/anaconda3

RUN git clone https://github.com/rdarie/rippleViewer /home/rippleViewerEnv/rippleViewer \
    && cd /home/rippleViewerEnv/rippleViewer \
    && chmod +x install_linux.sh \
    && install_linux.sh